# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONAr08gQmuqMjLqQdzZA34NOeyB37JvD
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

import matplotlib.pyplot as plt

data=pd.read_csv("car_sales_analysis_dataset.csv")
data

mileage=data["Mileage"]
mileage

price=data["Selling_Price"]
price

model=LinearRegression()

x=np.array(mileage).reshape(-1,1)
y=np.array(price).reshape(-1,1)

x

y

model.fit(x,y)

new_mileage=int(input("enter the new_mileage"))
new_data=np.array(new_mileage).reshape(-1,1)
answer=model.predict(new_data)
print(answer)

plt.scatter(x,y)
plt.xlabel("mileage")
plt.ylabel("price")
plt.show()