# -*- coding: utf-8 -*-
"""ML Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhMWLbE8T-rI7CUHe3ZhGQEx70PKbxmB
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

data=pd.read_csv("/content/StudentPerformanceFactors.csv")
data

hours_stuty=data["Hours_Studied"]
hours_stuty

score=data["Exam_Score"]
score

model=LinearRegression()

x=np.array(hours_stuty).reshape(-1,1)
y=np.array(score).reshape(-1,1)

x

y

model.fit(x,y)

new_hours_study=int(input("Enter your hours_study:"))
new_data=np.array(new_hours_study).reshape(-1,1)
y_answer=model.predict(new_data)
print("Your score is:",model.predict(new_data))

new_expirence=int(input("Enter your experience:"))
new_data=np.array(new_expirence).reshape(-1,1)
y_answer=model.predict(new_data)
print("Your salary is:",model.predict(new_data))

plt.scatter(x,y)


plt.xlabel("Hours_Studied")
plt.ylabel("Exam_Score")
plt.title("Hours_Studied vsExam_Score")
plt.show()