# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hje34lALmP-SsojnEnylFJl721GUtA6w
"""

import pandas as pd
data=pd.read_csv("/content/Sample - Superstore.csv",encoding="latin1")
data

m1=data.loc[0:5,"Row ID"]
m2=data.loc[0:5,"Region"]
m3=data.loc[0:5,"Sales"]
m1
m2
m3

Segment=data[["Segment"]]
Segment

import matplotlib.pyplot as plt
plt.bar(m1,m3)
plt.xlabel("Row ID")
plt.ylabel("Sales")
plt.show()

import matplotlib.pyplot as plt
plt.scatter(m1,m3)
plt.xlabel("Row ID")
plt.ylabel("Sales")
plt.show()

import matplotlib.pyplot as plt
plt.plot(m1,m3)
plt.xlabel("Row ID")
plt.ylabel("Sales")
plt.show()

import matplotlib.pyplot as plt
plt.plot(m2,m3,marker="o")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.show()

import numpy as np
plt.hist(m3,color="red",edgecolor="black")
plt.title("Sales")
plt.xlabel("Region")
plt.ylabel("sales")
plt.show()

companies = ['South','North','East','West']
market_share = np.array([35, 20, 20, 25])
plt.pie(market_share, labels=companies, autopct='%1.2f%%', startangle=90)
plt.title('Regions')
plt.show()

days = ['South','North','East','West']
times = ['Morning', 'Afternoon', 'Evening']

temps = np.array([
    [28, 36, 31],
    [27, 35, 30],
    [29, 37, 32],
    [28, 38, 33],
    [30, 39, 34],
    [31, 40, 35],
    [29, 37, 33]
])

# Create the heatmap
plt.imshow(temps, cmap='Greens_r', aspect='auto')# for equql cell
plt.colorbar(label="Temperature (°C)")
plt.title("chennai heat rate")



days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
times = ['Morning', 'Afternoon', 'Evening']

temps = np.array([
    [28, 36, 31],
    [27, 35, 30],
    [29, 37, 32],
    [28, 38, 33],
    [30, 39, 34],
    [31, 40, 35],
    [29, 37, 33]
])

# Create the heatmap
plt.imshow(temps, cmap='OrRd', aspect='auto')# for equql cell
plt.colorbar(label="Temperature (°C)")
plt.title("chennai heat rate")

import matplotlib.pyplot as plt
import numpy as np

# Simulated monthly rainfall data (in cm)
Sales = [261.9600,731.9400	,14.6200	,957.5775,22.3680	,25.2480,91.9600,29.6000	]
Profit= [41.9136,219.5820,6.8714,2.5164,4.1028,15.6332,19.3932,72.9480]


# Create a box plot
plt.boxplot([Sales,Profit], labels=['Sales','Profit'])
plt.show()

import re
text="this is my email abc@gmail.com and cde@gmail.com"
a=re.findall(r'\w{2,}+@\w{2,}\.\w{2,}',text)
a

import re
data ="this is my mail id's ,abc@gmail.com , cde@gmail.com and sri@gmail.com "
s=re.findall(r'\w{2,}+@\w{2,}\.\w{2,}',data)
s

text=input("Enter your text")
a=re.findall(r'sri',text)
if a:
 print("found")
else:
 print("not found")
a

txt="Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph ."
search=re.search(r'terms',txt)
print(search)

txt="my phone number is 3"
extract=re.search(r'\d',txt)
print(extract)

import re
data ="my number is 9363137871 and 9043679354"
s=re.findall(r'\d{2,}',data)
s

