# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KODvjndKoen-jBMMfFprSffrpkf_5JV3
"""

import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("/content/StudentPerformanceFactors.csv")
data

print(data.Exam_Score)

print(data.Hours_Studied)

print(data.Internet_Access)

print(data.Sleep_Hours)

print(data.Peer_Influence)

kurtosis_value = 	data['Exam_Score'].kurt()

print("Kurtosis Value:", kurtosis_value)

# Validation
if kurtosis_value > 0:
    print("Leptokurtic Distribution")
elif kurtosis_value < 0:
    print("Platykurtic Distribution")
else:
    print("Mesokurtic Distribution")

plt.figure(figsize=(10,5))
plt.hist(data['Exam_Score'], bins=30,color="purple")
plt.title("Students scores")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.show()

kurtosis=data['Sleep_Hours'].kurt()

print("kurtosis:",kurtosis)
if kurtosis>0:
  print("Leoptokurtic")
elif kurtosis <0:
  print("Platykurtic")
else:
  print("Mesokurtic")

plt.figure(figsize=(7,8))
plt.bar(data['Sleep_Hours'],color="green",height=3)
plt.title("Students sleep hours")
plt.xlabel("hours")
plt.ylabel("Frequency")
plt.show()

kurtosis_value = 	data['Previous_Scores'].kurt()

print("kurtosis_value:",kurtosis_value)
if kurtosis_value>0:
  print("Leptokutic")
elif kurtosis_value<0:
  print("Platykurtic")
else:
  print("Mesokurtic")

plt.figure(figsize=(8,5))
plt.hist(data['Previous_Scores'],bins=12,color="orange")
plt.title("Students previos_scores")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.show()

import numpy as np
from scipy.stats import kurtosis as k
profits=([100,120,150,200,4,1,2,5,3,2,6,5,4,3,3,1,2])
kurto=k(profits,fisher=True)
kurto1=k(profits,fisher=False)
mean_value=np.mean(profits)
max_value=max(profits)
min_value=min(profits)
if(kurto>0):
    print("heavy tail more distribution")
    if(max_value-mean_value)>(mean_value-min_value):
        print("big profits")
    else:
        print("big loss")
elif(kurto<0):
    print("low tail less distribution and low profit/loss")
else:
    print("normal distribution and normal profit/loss")

import matplotlib.pyplot as plt
plt.hist(profits, color=" red", edgecolor="black")
plt.title("Profit or Loss Distribution")
plt.xlabel("Profit Values")
plt.ylabel("Frequency")
plt.show()

mean_val=np.mean(profits)
median_val=np.median(profits)
mean_val

plt.plot(profits, color="purple")
plt.title("Profit or Loss Distribution")
plt.xlabel("Profit Values")
plt.ylabel("Frequency")
plt.axhline(mean_val, linestyle="--", linewidth=3)
plt.axhline(median_val, linestyle="dotted", linewidth=2)
plt.show()

import numpy as np
from scipy.stats import kurtosis as k
sales=[150,200,250,300,350,455,600,355,400,650,625,645]
kurto=k(sales,fisher=True)
kurto1=k(sales,fisher=False)
mean_value=np.mean(sales)
max_value=max(sales)
min_value=min(sales)

if(kurto>0):
    print("heavy tail more distribution")
    if(max_value-mean_value)>(mean_value-min_value):
        print("big profits")
    else:
        print("big loss")

    print("big profits")

elif(kurto<0):
    print("low tail less distribution and low profit/loss")
else:
    print("normal distribution and normal profit/loss")

import matplotlib.pyplot as plt
plt.hist(profits, color="blue", edgecolor="black")
plt.title("Profit or Loss Distribution")
plt.xlabel("Profit Values")
plt.ylabel("Frequency")
plt.show()