# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJ3XIztdRPSJcrNOWQyc9GPkMywcdIGp
"""

import matplotlib.pyplot as plt
from scipy.stats  import binom
import numpy as np
n=12
p=0.6
k=10
prob=binom.pmf(k,n,p)#shows highest possibilty is 0.06  which means 60% chance for sucess
print(prob)

x = np.arange(0, n + 1)
pmf_values = binom.pmf(x, n, p)
plt.bar(x, pmf_values, color="lightblue", edgecolor="black", label="Binomial PMF")

# highlight k = 10
plt.bar(k, prob, color="orange", edgecolor="black", label=f"k = {k}")

plt.xlabel("Number of successes")
plt.ylabel("Probability")
plt.title(f"Binomial distribution")
plt.legend()

plt.show()

from scipy.stats import binom
n=25
p=0.6
k=5
p=binom.cdf(k,n,p)
print(p)

from scipy.stats import zscore
# Data values
data = [10, 20, 30, 40, 50]
# Automatic Z-score calculation
result = zscore(data)
print("Data:", data)
print("Z-scores:", result)

from scipy.stats import zscore
data=[50,60,70,80,90,100]
result= zscore (data)
print("data",data)
print("Z-score",result)

from scipy.stats import zscore
data=[10,20,30]
result=zscore(data)
print("data",data)
print("Z-Score",result)
plt.scatter(data,result,color="orange",edgecolor="black")
plt.xlabel="data"
plt.ylabel="results"
plt.show()

import numpy as np
import pandas as pd
data=pd.read_csv(r"/content/mobile_sales.csv")
data
TotalRevenue=data["TotalRevenue"]
TotalRevenue
TotalRevenue_Of_mobile_sales = np.mean(TotalRevenue)

print("TotalRevenue Of mobile sales=",TotalRevenue_Of_mobile_sales )

sample = [25000,35000,45000,55000,65000,
          75000,85000,95000,104000,110000]

from scipy import stats
sample_mean = np.mean(sample)

ci = stats.t.interval(
    confidence=0.95,
    df=len(sample)-1,
    loc=sample_mean,
    scale=stats.sem(sample)
)

print("Sample Mean =", sample_mean)
print("95% Confidence Interval =", ci)

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import poisson as p
lam=10
k=15
pos=p.pmf(k,lam)
print("probability of getting 15 call in a minute:",pos)
x=np.arange(0,21)
fit=p.pmf(x,lam)
plt.bar(x,fit,color="black")
plt.title ("poisson distribution")
plt.xlabel ("no of calls in per minute")
plt.ylabel("probability")#chances
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import poisson as p
lam=20
k=13
pos=p.pmf(k,lam)
print("probability of getting 15 call in a minute:",pos)
x=np.arange(0,21)
fit=p.pmf(x,lam)
plt.bar(x,fit,color="green")
plt.title ("poisson distribution")
plt.xlabel ("no of calls in per minute")
plt.ylabel("probability")#chances
plt.show()